@baseUrl = https://8080-francielimr-aulaapiseme-o62wcgzx3b6.ws-us115.gitpod.io
###
GET {{baseUrl}}/alunos

###
POST {{baseUrl}}/alunos
Content-Type: application/json

{
    "nome": "Fulano de Tal"
}

###
GET {{baseUrl}}/alunos/1

###
PUT {{baseUrl}}/alunos/1
Content-Type: application/json

{
    "nome": "Fulano de Tal"
}
###
DELETE  {{baseUrl}}/alunos/1
